### PR TITLE
Hdfio fix getitem

### LINKED ISSUE #134: ProjectHDFio fails to open other Projects than it's direct parent
The `ProjectHDFio` is not able to open a standard pyiron Project other than it's parent project. Code to reproduce:
```
from pyiron_base import Project
pr=Project('test')
hdf=pr.create_hdf(pr.path,'test')
pr2=hdf['../..']
pr2.path == pr.path
```

I traced this down to the `__getitem__` of  the `FileHDFio`:
https://github.com/pyiron/pyiron_base/blob/74fc5115d6cbd1554f1cd4401ac9976921a487a9/pyiron_base/generic/hdfio.py#L834-L846

The `os.path.normpath('/hdf_root/../../')` returns '/'  since there is no directory super to root, thus `item_abs_list` will never be longer than 2.

### PR DESCRIPTION
**Pull request by niklassiemer**
Closes #134

### CODE REVIEW

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Review by pmrv — APPROVED** [review]

**Comment by jan-janssen** [comment]
Once this pull request is merged we can release a new version of `pyiron_base` and update `pyiron_atomistics` - @niklassiemer do you want to release the new version?

**Comment by niklassiemer** [comment]
Yes, I will do it.

**Comment by niklassiemer** [comment]
I  merged, and will wait until the test pass. Then I will tag the new version and make the conda release.

**Pull request merged**
