### PR TITLE
Replace copy_tree from distutils by copytree from shutil because dist…

### PR DESCRIPTION
**Pull request by samwaseda**
…utils is going to be removed from python 3.12

I stumbled upon [this article](https://stackoverflow.com/questions/10047521/how-to-copy-directory-with-all-file-from-c-xxx-yyy-to-c-zzz-in-python while trying to fix the [archiving problem](https://github.com/pyiron/pyiron_base/issues/1444) so I did the change.

### CODE REVIEW

**Review by liamhuber — APPROVED** [review]

**Comment by liamhuber** [comment]
Gah, mobile trouble getting my message attached to the review, sorry. Here it is:

The PR itself looks good to me, both in terms of motivation and execution. My only concern is that the archive tests are currently kind of spotty, yeah? Since this is such a straightforward PR, integrating it on top of any other changes to the archiving should be super straightforward, so maybe we want to hold off until those issues are closed, then merge in main and rerun newly improved tests? Just to make sure there's no side effects in the switch that we're oblivious too.

I'm only keeping half an eye on the archive/import-export conversation though, so I leave it your judgement whether this concern is overblown.

**Comment by samwaseda** [comment]
@liamhuber I’m asking for a review again because I decided to replace all occurrences of `distutils`. The one that I replaced, `strtobool` does not seem to have a proper replacement. On the other hand it’s an independent function of only a few lines, so I copied and pasted it from the source code, which I think is vertretbar.

Coming back to your concern, now I don’t think it’s related to files, but purely database entries. Besides the two functions `copy_tree`  and `copytree` are nearly identical, so I think it’s ok.

**Review by pmrv — COMMENTED** [review]
Please check under what license distutils is distributed and whether its compatible with our MIT, otherwise looks good to me.

**Comment by liamhuber** [comment]
> Please check under what license distutils is distributed and whether its compatible with our MIT, otherwise looks good to me.

BSD, but good point, before copy-pasting you should check that you can/what citations are needed.

The target library of shutils is just a standard library package, right? So almost certainly no worries there.

**Review by liamhuber — APPROVED** [review]

**Comment by liamhuber** [comment]
Dammit, I need to figure out how to approve with a message on mobile.

Anyhow, modulo double checking licensing, lgtm.

I do think this is exactly the sort of thing I would rather have in snippets than a particular pyiron module, but since snippets isn't published yet and moving it there will be trivial with my new gist, I have no problem putting it here for now if you don't want to wait.

**Comment by samwaseda** [comment]
> I do think this is exactly the sort of thing I would rather have in snippets than a particular pyiron module, but since snippets isn't published yet and moving it there will be trivial with my new gist, I have no problem putting it here for now if you don't want to wait.

I agree and exactly for the reason that it’s not published I kept it here.

**Pull request merged**
