### PR TITLE
Don't call pandas' to_hdf method

### PR DESCRIPTION
**Pull request by pmrv**
See #417 for discussion.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Just to understand this correctly, with this change it is possible to store pandas.Dataframes inside the DataContainer? If this works then I guess we could add a quick test and merge it.

**Comment by pmrv** [comment]
Yes, it should work, since the HDF layer also does a similar check, but I haven't tested it.

**Comment by jan-janssen** [comment]
I added a unit test - from my perspective this is ready to be merged.

**Comment by jan-janssen** [comment]
The unit test for linux passed - the windows ones currently seem to have a general issue https://github.com/pyiron/pyiron_base/issues/432

**Pull request merged**
