### PR TITLE
Use dill to save filter functions

### PR DESCRIPTION
**Pull request by pmrv**
I haven't tested this yet, so I'll leave it as a draft until I get around to it or someone urgently needs it.

### CODE REVIEW

**Comment by pmrv** [comment]
@niklassiemer I'm not sure how familiar you are with the table internals, but only me and @jan-janssen ever touch this file, so I thought I add you. ;)

**Comment by niklassiemer** [comment]
I never touched/had a look at them at all 😂 However, I will try my best to review this 😊

**Review by niklassiemer — COMMENTED** [review]
So you now always use dill to store the 'whole' function to get the data? I assume the function object will actually not be a lot larger than the string to generate that - from that perspective I think this is a good idea. How about the transferability? Is a `dill`ed object stable against moving to another machine/ version update? 
Other than that, I am not really sure what your update does. However, I did not see any big issues either :)

**Comment by pmrv** [comment]
I haven't actually looked at the size difference.  The main point is that storing functions as their "string" simply does not work generally and especially not for lambdas.  Dill at least promises that the format is stable.  I'm not sure that if they update the format it is in a backwards-compatible manner, but you can ask (via their API) for an older format to be read as well.  So we could think about specifying which version of the dill format we want, but we don't right now for the other functions, so I left it.

**Pull request merged**
