### PR TITLE
Use FileHDFio instead of ProjectHDFio to remove workaround

### LINKED ISSUE #229: load project_data on __init__
Concerning the recursive problem in #192 I just realized that the only reason to pass the `Project` itself to the `ProjectData` is the knowledge of the project path in `ProjectData`. All the advanced functionality of `ProjectHDFio` compared to a plain `FileHDFio` like database connection and knowledge of how to create a working directory are not used (and right now, they actually can't be used since the `ProjectHDFio` is not assigned). 
Therefore, we could either store `self._project_path` instead of  the whole `self._project` or just use the `self._project.path` to create a `FileHDFio` to read/write from.

### PR DESCRIPTION
**Pull request by niklassiemer**
closes #229

### CODE REVIEW

**Comment by liamhuber** [comment]
I like it, but it is somehow breaking the test for storing complex data (in this case a nested list). I played around with it for a few minutes, but don't understand what's going wrong. I'm going to play around with #234 for a bit this morning, so hopefully I'll pick up some insight into `InputList` that helps to resolve this. Automatic reading is absolutely the behaviour we want!

**Comment by liamhuber** [comment]
@niklassiemer I didn't explicitly find a solution, but I think that maybe we should wait until #216 is merged as that has a significant impact on the storage landscape.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
@niklassiemer and @liamhuber as https://github.com/pyiron/pyiron_base/pull/216 is merged I guess this one can now be merged as well.

**Review by liamhuber — APPROVED** [review]
Nice! I will merge 😄

**Pull request merged**
