### PR TITLE
Restore sub directories

### PR DESCRIPTION
**Pull request by samwaseda**
In the end it looks like @pmrv was right about [this statement](https://github.com/pyiron/pyiron_base/pull/1549#discussion_r1688597070). I asked ChatGPT to rewrite it and also to make tests. I hope now it's fine.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@samwaseda I have the feeling the current unit tests were not sufficient to find this error. Can you extend the unit tests so we at least get an error the next time somebody tries something like this?

**Comment by samwaseda** [comment]
> @samwaseda I have the feeling the current unit tests were not sufficient to find this error. Can you extend the unit tests so we at least get an error the next time somebody tries something like this?

If you are talking about `export_archive.py` in general, I agree, but I guess that's a different PR. For the problem that I encountered here, I guess the test I added here should be good enough.

**Comment by samwaseda** [comment]
Speaking of which, I realized a huge advantage of the function approach. You can copy and paste the code snippet to ChatGPT, state the problem, ask it to rewrite the code, and write unit tests accordingly. This should be more streamlined.

**Comment by jan-janssen** [comment]
> Speaking of which, I realized a huge advantage of the function approach. You can copy and paste the code snippet to ChatGPT, state the problem, ask it to rewrite the code, and write unit tests accordingly. This should be more streamlined.

I guess the streamlined solution is Github Co-Pilot - maybe @srmnitc can comment on this.

**Comment by jan-janssen** [comment]
The windows tests fail:
```
======================================================================
FAIL: test_copy_h5_files (archiving.test_export.TestPack.test_copy_h5_files)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\runneradmin\miniconda3\envs\my-env\Lib\unittest\mock.py", line 1390, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\pyiron_base\pyiron_base\tests\unit\archiving\test_export.py", line 118, in test_copy_h5_files
    mock_makedirs.assert_has_calls(expected_makedirs_calls, any_order=True)
  File "C:\Users\runneradmin\miniconda3\envs\my-env\Lib\unittest\mock.py", line 997, in assert_has_calls
    raise AssertionError(
AssertionError: 'makedirs' does not contain all of (call('/mock/dst/.', exist_ok=True), call('/mock/dst/subdir1', exist_ok=True), call('/mock/dst/subdir2', exist_ok=True)) in its call list, found [call('/mock/dst\\.', exist_ok=True), call('/mock/dst\\subdir1', exist_ok=True), call('/mock/dst\\subdir2', exist_ok=True)] instead

----------------------------------------------------------------------
```

**Comment by samwaseda** [comment]
> > Speaking of which, I realized a huge advantage of the function approach. You can copy and paste the code snippet to ChatGPT, state the problem, ask it to rewrite the code, and write unit tests accordingly. This should be more streamlined.
> 
> I guess the streamlined solution is Github Co-Pilot - maybe @srmnitc can comment on this.

Ah right. I used Co-Pilot for the actual writing of the snippets (and I didn't particularly like it at that time), but I haven't tried it for doc string or unit tests.

**Comment by srmnitc** [comment]
> > Speaking of which, I realized a huge advantage of the function approach. You can copy and paste the code snippet to ChatGPT, state the problem, ask it to rewrite the code, and write unit tests accordingly. This should be more streamlined.
> 
> I guess the streamlined solution is Github Co-Pilot - maybe @srmnitc can comment on this.

I use CoPilot extension on VScode. This way it already gets the whole code context and therefore can make better suggestions.

**Review by pmrv — APPROVED** [review]
Good to see I am not yet replaced by the machine.  Took me a bit to understand the mocking, but it seems neat.

I don't follow the dot business.  Is it because normpath drops `/.` on unix, but not on windows?

**Comment by samwaseda** [comment]
> I don't follow the dot business. Is it because normpath drops `/.` on unix, but not on windows?

Yes. It's just horrible

**Pull request merged**
