### PR TITLE
Changes to InputList

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by pmrv** [comment]
This is the changes merged since #70? I'll have a look then, that nothing got mangled.

**Comment by jan-janssen** [comment]
This starts with the renaming from Inputlist to Datacontainer

**Comment by liamhuber** [comment]
I'm desperately waiting for this functionality.

i-need-more-code

We're just holding off until the end of the potentials workshop, or?

**Comment by pmrv** [comment]
> I'm desperately waiting for this functionality.
> 
> i-need-more-code
> 
> We're just holding off until the end of the potentials workshop, or?

Currently debugging the issue that came up with sphinx, otherwise this can go in my opinion.

**Review by pmrv — APPROVED** [review]
I can't reproduce the error from sphinx by the message alone, so I'd suggest the following.

1. bump pyiron_base patch-level version
2. wait for dependabot to create the PR on pyiron_contrib/atomistics
3. rename all occurrences of `InputList` to `DataContainer` and debug any issues that might pop up in those PRs
3.1/2 this might include going back to pyiron_base to fix any regressions introduced by this PR and bumping patch-level again.

**Comment by liamhuber** [comment]
> I can't reproduce the error from sphinx by the message alone, so I'd suggest the following.
> 
> 1. bump pyiron_base patch-level version
> 2. wait for dependabot to create the PR on pyiron_contrib/atomistics
> 3. rename all occurrences of `InputList` to `DataContainer` and debug any issues that might pop up in those PRs
>    3.1/2 this might include going back to pyiron_base to fix any regressions introduced by this PR and bumping patch-level again.


fire

@pmrv yes please.

**Comment by jan-janssen** [comment]
> I can't reproduce the error from sphinx by the message alone, so I'd suggest the following.
> 
> 1. bump pyiron_base patch-level version
> 2. wait for dependabot to create the PR on pyiron_contrib/atomistics
> 3. rename all occurrences of `InputList` to `DataContainer` and debug any issues that might pop up in those PRs
>    3.1/2 this might include going back to pyiron_base to fix any regressions introduced by this PR and bumping patch-level again.

I thought this should be addressed by https://github.com/pyiron/pyiron_base/pull/237

**Comment by pmrv** [comment]
> > I can't reproduce the error from sphinx by the message alone, so I'd suggest the following.
> > 
> > 1. bump pyiron_base patch-level version
> > 2. wait for dependabot to create the PR on pyiron_contrib/atomistics
> > 3. rename all occurrences of `InputList` to `DataContainer` and debug any issues that might pop up in those PRs
> >    3.1/2 this might include going back to pyiron_base to fix any regressions introduced by this PR and bumping patch-level again.
> 
> I thought this should be addressed by #237

Yes, I'll try to make it work today. For some reason I can't seem to get pyiron_atomisitics with all the deps correctly installed in the test environment.

**Comment by liamhuber** [comment]
The pyiron_contrib compatibility test fails right at the environment creation. I looked at `.ci_support/environment.yml` for both repos and still don't see what the issue is. Could someone (@muh-hassani?) investigate this on Monday or Tuesday and teach me what I'm missing?

**Comment by pmrv** [comment]
The `pyiron_atomistics` tests pass for this, so I'll merge this today. Thanks to @liamhuber for fixing the mangled tests.

**Comment by liamhuber** [comment]
We don't know yet whether the contrib tests pass though, since building the env fails

**Comment by jan-janssen** [comment]
@liamhuber and @pmrv I fixed the integration tests

**Pull request merged**
