### PR TITLE
Replace eval with explicit indices

### PR DESCRIPTION
**Pull request by pmrv**
This should fix [this error](https://github.com/pyiron/pyiron_contrib/pull/65).  Running the tests locally I'm getting some problems with `copy_to` that I don't understand yet.

### CODE REVIEW

**Comment by Leimeroth** [comment]
Can't import InputList anymore.

ImportError: cannot import name 'InputList' from 'pyiron_base' (/home/niklas/git_projects/pyiron_base/pyiron_base/__init__.py)

Edit: Importing still works with master branch and I don't see why it does not with this one

**Comment by pmrv** [comment]
It seems I created this PR from an older master, should be fixed.

**Comment by Leimeroth** [comment]
The notebook for the workshop works again now, but loading old jobs got broken. I got this error message:

```
~/git_projects/pyiron_base/pyiron_base/project/generic.py in load(self, job_specifier, convert_to_object)
    769             s.logger.warning("Job '%s' does not exist and cannot be loaded", job_specifier)
    770             return None
--> 771         return self.load_from_jobpath(
    772             job_id=job_id, convert_to_object=convert_to_object
    773         )

~/git_projects/pyiron_atomistics/pyiron_atomistics/project.py in load_from_jobpath(self, job_id, db_entry, convert_to_object)
    207             GenericJob, JobCore: Either the full GenericJob object or just a reduced JobCore object
    208         """
--> 209         job = super(Project, self).load_from_jobpath(
    210             job_id=job_id, db_entry=db_entry, convert_to_object=convert_to_object
    211         )

~/git_projects/pyiron_base/pyiron_base/project/generic.py in load_from_jobpath(self, job_id, db_entry, convert_to_object)
    790         if job_id:
    791             job = jobpath(db=self.db, job_id=job_id, user=self.user)
--> 792             job = job.load_object(
    793                 convert_to_object=convert_to_object, project=job.project_hdf5.copy()
    794             )

~/git_projects/pyiron_base/pyiron_base/job/core.py in load_object(self, convert_to_object, project)
    547             with project.open("..") as job_dir:
    548                 job_dir._mode = "a"
--> 549                 return self.to_object(project=job_dir, job_name=self._name)
    550         return self
    551 

~/git_projects/pyiron_base/pyiron_base/job/core.py in to_object(self, object_type, **qwargs)
    482                 + "\" is empty, so it can not be loaded."
    483             )
--> 484         return self.project_hdf5.to_object(object_type, **qwargs)
    485 
    486     def get(self, name):

~/git_projects/pyiron_base/pyiron_base/generic/hdfio.py in to_object(self, class_name, **qwargs)
   1349 
   1350         obj = self.create_instance(class_object, **qwargs)
-> 1351         obj.from_hdf(
   1352                 hdf = self.open(".."),
   1353                 group_name = self.h5_path.split('/')[-1]

~/git_projects/pyiron_contrib/pyiron_contrib/atomistic/atomicrex/atomicrex_job.py in from_hdf(self, hdf, group_name)
     59         """        
     60         super().from_hdf(hdf=hdf, group_name=group_name)
---> 61         self.input.from_hdf(hdf=self.project_hdf5)
     62         self.potential = self.project_hdf5["potential"].to_object()
     63         self.structures.from_hdf(hdf=self.project_hdf5)

~/git_projects/pyiron_base/pyiron_base/generic/datacontainer.py in from_hdf(self, hdf, group_name)
    659                 items.append( (*normalize_key(n), hdf[n]))
    660             for g in hdf.list_groups():
--> 661                 items.append( (*normalize_key(g), hdf[g].to_object()))
    662             for _, k, v in sorted(items, key=lambda x: x[0]):
    663                 self[k] = v

~/git_projects/pyiron_base/pyiron_base/generic/hdfio.py in to_object(self, class_name, **qwargs)
   1348             self["TYPE"] = str(class_object)
   1349 
-> 1350         obj = self.create_instance(class_object, **qwargs)
   1351         obj.from_hdf(
   1352                 hdf = self.open(".."),

~/git_projects/pyiron_base/pyiron_base/generic/hdfio.py in create_instance(self, cls, **kwargs)
   1317         init_args.update(kwargs)
   1318 
-> 1319         return cls(**init_args)
   1320 
   1321     def to_object(self, class_name=None, **qwargs):

TypeError: __init__() missing 4 required positional arguments: 'conv_threshold', 'max_iter', 'gradient_epsilon', and 'name'
```

I guess this could be somehow related to the *args and **kwargs in nested InputLists?

**Comment by pmrv** [comment]
Yes, when read from HDF, `InputLists` are instantiated empty and then populated with `from_hdf`, so this fails because no arguments are given, but `AtomicrexAlgorithm` expects them.

I would suggest we stay with `pyiron_base==0.1.48` for the workshop and iron these things out after it.  @jan-janssen , thoughts?

There's some more details on how to the HDF5 interface works [here](https://pyiron-base.readthedocs.io/en/latest/source/hdf5.html).  This suggests you could add an `from_hdf_args` on `AtomicrexAlgorithm` that reads `conv_threshodl`, etc. from the HDF5 and returns them as parameters and then override `from_hdf` to do nothing.

**Comment by jan-janssen** [comment]
@pmrv With the current dependencies `>=` I would suggest that we release a new version which reverts the `InputList` part.

**Comment by pmrv** [comment]
> @pmrv With the current dependencies `>=` I would suggest that we release a new version which reverts the `InputList` part.

I think reverting the `pyiron_base` bump is probably easier than reverting the 3 PR we merged here in the mean time, but fine with either. 

In any case this PR is independent of the InputList, so I'll keep it open.

**Pull request closed without merging**
