### PR TITLE
Use self.__class__ to instantiate another instance of Project.

### PR DESCRIPTION
**Pull request by niklassiemer**
To enable inheritance of methods like copy. 
Replacing PR #143.

### CODE REVIEW

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
@niklassiemer As the other pull requests are related to redesigning the user interface - e.g. manipulating the `__dir__()` method - I guess it makes sense to release a new pyiron_base version with these changes. Can you create a new release?

**Comment by niklassiemer** [comment]
So releasing a new release now before we start editing the `__dir__`?

**Comment by jan-janssen** [comment]
> So releasing a new release now before we start editing the `__dir__`?

yes

**Comment by niklassiemer** [comment]
> > So releasing a new release now before we start editing the `__dir__`?
> 
> yes

Ok, I will make a new release :)

**Pull request merged**
