### PR TITLE
Document gotcha in analysis_project

### PR DESCRIPTION
**Pull request by pmrv**
Just a docstring touch up

### CODE REVIEW

**Comment by niklassiemer** [comment]
I am not really used to work with pyiron tables so far. However, the setter uses `system_function_lst=self._system_function_lst` which would retain the analysis functions, wouldn't it?

**Comment by pmrv** [comment]
Honestly this is from February and I just found the commit... I'll have a look at it again tomorrow, but I thought this tripped me up before.

**Comment by pmrv** [comment]
I've checked just now that this is still an issue.  I agree that the code appears to catch this, but I don't have time right now to debug this.  I would merge this and add an "unsolved" tag, so this can be fixed later, if no one complains loudly.

**Comment by pmrv** [comment]
[Nevermind.](https://github.com/pyiron/pyiron_base/pull/198)

**Pull request closed without merging**
