### PR TITLE
project pack raise warning when destination_path matches project path

### LINKED ISSUE #1046: Danger with project pack
The following example code: 
```
from pyiron import Project
pr = Project("/Users/janssen/pyiron/projects/2023/2023-02-23-transfer/Gd_PBE_DZP")
pr.pack(destination_path="Gd_PBE_DZP")
```
Deletes the folder `Gd_PBE_DZP` and all calculations inside, without raising a warning.

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by samwaseda** [comment]
I think the right way to solve this problem is to properly implement [this PR](https://github.com/pyiron/pyiron_base/pull/886) @srmnitc

**Comment by srmnitc** [comment]
@samwaseda Agreed, I will pick it up again and finish shortly.

**Comment by jan-janssen** [comment]
> @samwaseda Agreed, I will pick it up again and finish shortly.

Can you give a rough estimate when it is going to be finished? I now have people here at LANL who use the `pack()` functionality to transfer calculation between different clusters and we do not want to wait another four month. So my preferred option would be to merge this pull request and then rebase the other pull request based on this one.

**Comment by srmnitc** [comment]
I could finish it by next week end, but feel free to merge this if that is too long. I have no qualms with the merging of this pull request.

**Pull request merged**
