### PR TITLE
Updates for Scriptjob

### PR DESCRIPTION
**Pull request by jan-janssen**
```
import os
from pyiron_base import Project

script_py = """\
from pyiron_base import load, dump
input_dict = load()
output_dict = input_dict.copy()
dump(output_dict)
"""

file_name = "test.py"
with open(file_name, "w") as f:
    f.writelines(script_py)

pr = Project("test")
job = pr.create.job.ScriptJob("script")
job.script_path = os.path.abspath(file_name)
job.input["a"] = 1
job.input["b"] = [1,2,3]
job.run()

data_container = job["output"].to_object().to_builtin()
```

In combination with https://github.com/pyiron/pyiron_base/pull/637 this should cover the implementation of new classes.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Based on these changes I created a "low-code" example https://github.com/jan-janssen/pyiron-dynamic . In the example the developer only needs to create a `input.json` file for the default inputs and a `script.py` file for interfacing with the simulation code. The rest is handled by the functionality in `pyiron_dynamic`. That is less than 50 lines which include all the magic of dynamically generating classes on-the-fly. Currently these examples do not work on the queuing system, but if we integrate this functionality inside `pyiron_base` that should be no issue. @niklassiemer  and @muh-hassani  maybe the two of you can collect some feedback if this would address the needs of users from other disciplines.

**Comment by jan-janssen** [comment]
I fixed the tests, so this pull request is ready for review now.

**Comment by jan-janssen** [comment]
I moved the dynamic creation of new classes to a separate pull request https://github.com/pyiron/pyiron_base/pull/705

**Review by niklassiemer — APPROVED** [review]
LGTM!

**Pull request merged**
