### PR TITLE
Fixes for the `pack()` and `unpack()` method

### LINKED ISSUE #1402: bug in project packing
Dear all,

I've recently found a bug in the pack function of the pyiron project. What I wanted to do was to select a few jobs from an existing project, copy them to a new project, and then pack the new project. Here is how I did it:
`pr_old = Project('Mg_water_equilibrium')`
`pr_archive = Project('../../../ptmp/pyiron-publication-template/archive')`
`job_new = job.copy_to(project=pr_archive)`
`pr_archive.pack(destination_path="../../../ptmp/pyiron-publication-template/save", copy_all_files=True)`
Here the archive project path should be `'/cmmc/u/jyang/ptmp/pyiron-publication-template/archive`, however, the pack functions tries to read the files from the folder of the notebook (`/cmmc/u/jyang/pyiron/Mg/Ca_in_Mg_0001`) and I get the following error:
Screen Shot 2024-03-28 at 3 57 25 PM

### PR DESCRIPTION
**Pull request by jan-janssen**
@jyang2009 based on our discussion I created a couple of fixes for the `pack()` and `unpack()` method. Can you check if these resolve the issues you had with archiving on `ptmp`?

### CODE REVIEW

**Comment by jyang2009** [comment]
Hi Jan,

I've tested this fix but got a new error when using the copy_to function. I copy the error below.
Screen Shot 2024-04-05 at 1 45 41 PM

Best,
Jing

**Comment by jan-janssen** [comment]
@jyang2009 Can you provide a bit more details about the commands you were executing that resulted in this error?

**Comment by jyang2009** [comment]
Hi Jan,

I just used the code that I used to copy jobs to the new project, which was working previously.
`pr_archive = Project("archive")`
`job_new = job.copy_to(project=pr_archive)`

**Comment by jan-janssen** [comment]
> Hi Jan,
> 
> I've tested this fix but got a new error when using the copy_to function. I copy the error below. 
> 
> Best, Jing

Hi Jing, 

I am sorry for the delay. The error message basically says, that `pr_archive` is not a recognised data type. You can check the data type using: 
```
type(pr_archive)
```
My assumption would be it is just a `str` or a `Path` object. In those cases you can create a project from it using: 
```
pr_archive=Project(pr_archive)
```
This should resolve this issue. 

Best, 

Jan

**Comment by jan-janssen** [comment]
@samwaseda Originally I was waiting for feedback from @jyang2009 if this solves her problem, as from my side this looks ready to be merged.

**Review by samwaseda — APPROVED** [review]
I would have probably changed the error message and kept the current functionality, but I'm ok with the suggested solution.

**Comment by samwaseda** [comment]
Side note: I don't think the csv file should be separated from the tar file, so I will probably remove it entirely in [this PR](https://github.com/pyiron/pyiron_base/pull/1440)

**Comment by samwaseda** [comment]
Did this one actually solve the issue @jyang2009 ? Otherwise I would like to revert it because I find it actually pretty dangerous that it looks for the csv file everywhere.

**Comment by samwaseda** [comment]
@jyang2009 sort of confirmed that the error that she was getting was not related to `unpack`. So I'm gonna partly revert the changes here.

**Pull request merged**
