### PR TITLE
Simplify submitting functions to the queue

### PR DESCRIPTION
**Pull request by jan-janssen**
Now that the `DataContainer` is finally able to store arbitrary objects - at least with python 3.11 and the latest version of h5io https://github.com/h5io/h5io/releases/tag/h5io-0.2.1 - I finally come back to the FunctionContainer pull request https://github.com/pyiron/pyiron_base/pull/1080 .

Example: 

```python
def test_function(a, b=8):
    return a+b

from pyiron_base import Project
pr = Project("test")
job = pr.wrap_python_function(test_function)
job.input["a"] = 4
job.input["b"] = 5
job.run()
job.output["result"] 
```

Features: 

* Any kind of function can be wrapped. In the background I am using `cloudpickle` to pickle the functions. 
* Job names are automatically generated with the md5 hash function, so multiple calls of the same function with different parameters result in different jobs. Still when the same job is submitted with the same function and the same parameters, then the job is correctly reloaded. 
* Functions can be executed in the background using `job.server.run_mode.non_modal = True` or submitted to the queuing system. 
* The default arguments of the function are copied to `job.input`. Parameters which do not have a default, are set to `None`.

### CODE REVIEW

**Comment by jan-janssen** [comment]
This functionality is designed to help users to transition their workflows from the traditional job based model to the more modern functional approach in https://github.com/pyiron/pyiron_workflow . With the current pull request, I introduce the option to already include functions in our current workflows using `pyiron_base`.

**Comment by jan-janssen** [comment]
In the same way the wrapped function can also be used just like a `function`: 
```python
test_function_wrapped = pr.wrap_python_function(test_function)
test_function_wrapped(4, b=6)
```

**Comment by jan-janssen** [comment]
@srmnitc Would you have time to review this pull request? My hope is that in addition to https://github.com/pyiron/pyiron_base/pull/1286 the changes introduced here help to wrap more workflows with pyiron

**Comment by srmnitc** [comment]
> @srmnitc Would you have time to review this pull request? My hope is that in addition to #1286 the changes introduced here help to wrap more workflows with pyiron

sorry I couldnt get around to this. I am still not fully back to work yet..

**Comment by jan-janssen** [comment]
> sorry I couldnt get around to this. I am still not fully back to work yet..

@srmnitc No problem, I just wanted to merge these pull requests for the release of `pyiron_base=0.7.0`

**Pull request merged**
