### PR TITLE
[patch] replace logger with snippets version

### PR DESCRIPTION
**Pull request by liamhuber**
i.e. pyiron_base.state.logger.logger with pyiron_snippets.logger.logger. The original location leaves a re-direct for backwards compatibility.

### CODE REVIEW

**Comment by liamhuber** [comment]
The linter got rid of my redirect. I am going to get rid of it in the next PR anyhow, but I just want to point out that the robot is obliviously wrecking my software engineering choices. Sometimes an unused import is intentional.

Screen Shot 2024-06-03 at 10 26 07

**Comment by liamhuber** [comment]
FFS, is there a flag to stop the damned bot?

**Comment by liamhuber** [comment]
Ok, I tried bypassing the linter by adding `--no-verify` on my local machine before pushing the commit, but this doesn't work. I don't see how to bypass the linter when it's operating on the remote machine, so I'm just going to give in and "trick" it. 👎 👎

**Comment by jan-janssen** [comment]
> i.e. pyiron_base.state.logger.logger with pyiron_snippets.logger.logger. The original location leaves a re-direct for backwards compatibility.

I thought we agreed to completely remove the classes replaced by `pyiron_snippets`.

**Comment by liamhuber** [comment]
> > i.e. pyiron_base.state.logger.logger with pyiron_snippets.logger.logger. The original location leaves a re-direct for backwards compatibility.
> 
> 
> 
> I thought we agreed to completely remove the classes replaced by `pyiron_snippets`. 

Yes, but instead of having three compatibility breaking commits, I opted to go for three backwards-compatible patches and then a single PR to remove all the compatibility shortcuts.

**Pull request merged**
