### PR TITLE
Introduce _new_instance method.

### PR DESCRIPTION
**Pull request by niklassiemer**
The _new_instance method returns a new instance of the current class via the __class__ attribute.
This allows to 'just' inherit methods like copy without the need to rewrite the same code again for each subclass.

### CODE REVIEW

**Review by pmrv — APPROVED** [review]
I think it's a great idea!  

I think just replacing `Project` with `self.__class__` would be enough, but I don't feel strongly about this.  Are you expecting to make a sub-class of `Project` where the arguments would change?

**Comment by niklassiemer** [comment]
I do not feel strong about this part, either. However, the first time reading the `self.__class__()` snipped I was confused what is going on and within a `_new_instance` function this would be more obvious. Therefore, for me this increases readability. For the other part, I do not want to change the arguments of Project and I clearly hope we will never have to, since this would be very confusing if one `Project` behaves very different from another.

**Comment by jan-janssen** [comment]
To explain the bug in the notebooks: 
```
Traceback (most recent call last):
105
  File "/usr/share/miniconda/envs/test/bin/papermill", line 10, in <module>
106
    sys.exit(papermill())
107
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
108
    return self.main(*args, **kwargs)
109
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main
110
    rv = self.invoke(ctx)
111
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
112
    return ctx.invoke(self.callback, **ctx.params)
113
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
114
    return callback(*args, **kwargs)
115
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
116
    return f(get_current_context(), *args, **kwargs)
117
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/cli.py", line 240, in papermill
118
    execute_notebook(
119
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/execute.py", line 87, in execute_notebook
120
    nb = load_notebook_node(input_path)
121
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/papermill/iorw.py", line 410, in load_notebook_node
122
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
123
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/__init__.py", line 77, in reads
124
    validate(nb)
125
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/validator.py", line 268, in validate
126
    for error in iter_validate(nbdict, ref=ref, version=version,
127
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/validator.py", line 303, in iter_validate
128
    validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
129
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/validator.py", line 57, in get_validator
130
    schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
131
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/validator.py", line 94, in _get_schema_json
132
    with open(schema_path) as f:
133
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbformat/v4/nbformat.v4.4.schema.json'
```
Basically `nbformat` 5.1.0 and 5.1.1 are broken and 5.1.2 is going to fix this. For more details https://github.com/conda-forge/nbformat-feedstock/issues/24

**Comment by jan-janssen** [comment]
I go with Marvin here, if we want to extend the readability we can add it as an inner function, but then the same could be addressed by a comment. But if we have many functions each with their own hidden sub functions, then this can be very confusing in particular when the functions inside the class are grouped by public and private functions. Therefore I would prefer to remove the additional function.

**Comment by niklassiemer** [comment]
Ok, I will close this here and just add the smaller change in another PR

**Pull request closed without merging**
