### PR TITLE
Introduce black formatting workflow triggered by `format_black` label

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by niklassiemer** [comment]
The Format black workflow fails if there is nothing to do (And I cannot change this). However, one probably adds the label if there is a failing Black test :) Testing if does the correct thing (and not fail) in #619

**Comment by niklassiemer** [comment]
Seems to work fine. One thing: The commit with the changes due to black formatting does not retrigger CI (if we stick to the GitHub Token) - I would be fine with this since black does not change behavior. However, one has to check for other than 'black' failed tests on the previous commit! We could also use another token (e.g. Dependabot token) to push the commit - this should retrigger CI.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by niklassiemer** [comment]
Let's see if it works: #619

**Comment by niklassiemer** [comment]
Not yet...

**Comment by niklassiemer** [comment]
It seems to need the same token on checkout?! Now it should work according to my tests :)

**Pull request merged**
