### PR TITLE
Hackathon docs changes

### PR DESCRIPTION
**Pull request by liamhuber**
Let's use this space to agree on a general structure and divvy up work, and then make PRs into it

First steps:

0. [ ] Landing page sales-pitch
1. [ ] @pmrv  Identify relevant sections of the handbook: https://github.com/eisenforschung/pyiron-meeting-mpie/tree/master/handbook
2. [ ] Move example notebooks to tutorial section
3. [ ] Update installation -- Han
4. [ ] Add how-tos:
     1. [ ] Job management
          1. loop through and generate jobs iteratively
          2. job renaming
          3. job copying
          4. remove a job
          5. kill a job
          6. compress/decompress a job
          7. Anything else common to terminal users (job monitoring, statuses, tailing jobs)
     9. [ ] Project handling
     10. [ ] pack/unpack
     11. [ ] Coupling to a new code as jobs
     12. [x] Make pure-python jobs
     13. [ ] Accessing/modifying hdf5
     14. [ ] pr.job_table() - also note (briefly) the quirks with running jobs which did not issue a SIGTERM in time due to walltime crash. Tell user how to avoid this `pr.job_table(auto_refresh_job_status = True)`
     15. [ ] pyiron tables?
     16. [ ] speed up iterative functions by avoiding job-object reconstructions -> direct peeking via hdf5/lazy mode for functions
17. [ ] Concepts/Spec
     1. [ ] tab completion to search for functionality
     2. [ ] peek the docstring with `??` `pr.job??`
     3. [ ] single point of import?

### CODE REVIEW

**Comment by pmrv** [comment]
# pyiron documentation strategy meeting

## What is documentation? For whom? For what purpose?

- Set of examples for new users to get started
    - e.g. Murnaghan
- Experienced users to look for new possibilities
- Developers to know how the software works
- How-to
- Tutorial
- Short description of how you go about
- Define promises about the interface
  - What can go in, what can go out, how it will execute (fast, slow, remotely, right now, etc.)
  - For users, so they know what they can expect
  - For developers, so they know the limits of how they can modify stuff _without breaking user expectations_
- Place that shows capabilities of the software
    - Searchable
    - Split up by topic
- Target user groups: new/experienced/dev, student/post-doc/group leader, ...

Docs we like:
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
    - Examples
    - Searchable keyword
    - Related elements
    - User guide -> step by step
    - Combine the numpy with other codes
    - numpy for matlab users
- [sklearn](https://scikit-learn.org/stable/)
    - Easily sorted into different topics, ala Mira's suggestion above "Place that shows capabilities"

- Points regarding pyiron.org
    - Documentation link should be a drop down that gives the links all sub readthedocs (base, atomistics, contrib, ...)
    - Should have another tab about high level view *text only*
    - should have also links to the youtube.com
    - virtual course link should list all workshops
        - Potentials 2021  https://pyiron.org/potentials-workshop-2021
        - Potentials 2022  https://pyiron.org/potentials-workshop-2022

- rough outline for a new pyiron.readthedocs.org
    - Philosophy: re-publish base info (with a dev-controlled blacklist), then show domain-specific data
    - Eg: pyiron_xyz
        - XYZ landing page
        - Installation
        - How-To / FAQ
        - Tutorial
        - API Reference
        - Developer guide
        - Application Topics (Full examples which redirect for specifics to how to):
            - full fledged physics 
            - can be read from top to bottom
            - not necessarily directly usable
            - show off stuff

    - Base
        - Marvin, Liam, Han
    - Atomistics
        - Jan, Sarath, Sam, Marian
    - Continuum
        - Sam, Marian, (pseudo Liam)
    - Experimental
        - Sarath

    - how to is synthesized from old Handbook
    - pyiron.readthedocs.org also has the merged contents of all
    - technical note: probably solvable via git submodules:
        - each domain has their own docs/
        - pyiron main repo pulls from sub domain docs/ and organizes to their contents new with its own toc
        - https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository


Commonalities of things we do and don't like:
-

Technical tools:
- Can we develop a set of tags to identify different documentation elements -- e.g. notebooks -- and make them searchable?
- Splitting things up: a small set of "best practices" examples, and a larger set of "you can do this, but there might be new/better ways these days" examples

## Levels of documentation 
- high level - why should I care about pyiron? (if I am an experimentalist, group leader, ... )
- mid level - How to calculate a specific material property? (short explanation not full example notebooks )
- low level - 

## Examples sorted by interest group 
- electro chemistry 
- continuum simulation 
- experimental 

## Topics to include:

- Structure Generation 
    - grainboundaries 
    - sqs structures
    - ASE structures
    - water structure 
    - Randspg structures 
    - Analysis:
        - CNA, aCNA
        - Vacancy
        - Neighbours

- Simulation Codes
    It's important to also address this to advanced users of resp. code
    - LAMMPS 
    - Sphinx 
    - VASP 
    - GPAW 
    - DAMASK

- Material Properties 
    - Quasi-harmonic Approximation 
    - Elastic Constants 
    - Murnaghan 
    - Stacking faults 
    - Paramagnetic structures 
    - Phase diagrams 
    - interface energies 
    - solutes (interstitial & substitutional) at grainboundaries 
    - fitting machine learning potentials 
    - thermodynamic integration 
    - 

- Technical configuration 
    - submit to queues 
    - setup on HPC
    - remote HPC 
    - archiving with pack and unpack 
    - database 

- Trouble shooting 
    - pyiron configuration 
    - 

- Architecture 
    - how pyiron works internally 

- New classes 
    - Template Job

**Comment by ligerzero-ai** [comment]
- [ ] Accessing the hdf5
- [ ] Modifying the hdf5

**Comment by jan-janssen** [comment]
While I am primarily contributing to the `pyrion_atomistics` documentation, here are a couple of examples I would like to add for `pyiron_base`: 
* https://github.com/pyiron-dev/pyiron-dynamic-executable
* https://github.com/pyiron-dev/pyiron-dynamic
* https://github.com/pyiron-dev/pyiron-db-change
* https://github.com/pyiron-dev/pyiron-worker
* [pyiron table](https://github.com/pyiron/pyiron_atomistics/blob/main/notebooks/data_mining.ipynb)

**Comment by jan-janssen** [comment]
Maybe also relevant for the pyiron_base documentation is the corresponding chapter from my PhD thesis - chapter 4 - which summarizes some of the general concepts of pyiron: 
https://digital.ub.uni-paderborn.de/hs/content/titleinfo/6098963

**Comment by jan-janssen** [comment]
One part which might be helpful for this project is the documentation for the queuing system adapter `pysqa` - this is now available in https://pysqa.readthedocs.io

**Pull request closed without merging**
