### PR TITLE
Fix run_time_to_db() for jobs submitted to remote computers

### PR DESCRIPTION
**Pull request by jan-janssen**
@ligerzero-ai

### CODE REVIEW

**Review by niklassiemer — COMMENTED** [review]
That solution would be ok for me. However, couldn't we shift the 'is a db available check' into the database interface itself?

**Comment by ligerzero-ai** [comment]
wip - we are trying to hunt down a phantom error

**Comment by ligerzero-ai** [comment]
It should work:

image

Fetching with `wait_for_jobs` works.

Remote system with PBSPro queueing system. Still needs to be tested for slurm

**Comment by jan-janssen** [comment]
> That solution would be ok for me. However, couldn't we shift the 'is a db available check' into the database interface itself?

While I agree that cleaning up the database interface to handle the specific case of a local installation with database and a remote installation without an database. This pull request list primarily focused on solving the issues that @Leimeroth reported quite some time ago.

**Comment by jan-janssen** [comment]
> It should work:

To clarify - it works if the calculation finishes successful, currently there is still an issue for failed or not converged calculation. This still needs to be addressed.

**Pull request merged**
