### PR TITLE
fix pyiron_atomistics project level create_job()

### LINKED ISSUE #1029: dots in job names fails for GenericMaster jobs
This works: 
```
import os
from pyiron_atomistics import Project
pr = Project("test")
job = pr.create.job.Lammps("lmp1.2")
job.structure = pr.create.structure.ase.bulk("Al", cubic=True)
job.run()
os.listdir(os.path.dirname(job.project_hdf5.file_name))
>>> ['lmp1d2_hdf5', 'lmp1d2.h5']
```

But this fails: 
```
import os
from pyiron_atomistics import Project
pr = Project("test")
pr.remove_jobs(recursive=True, silently=True)
job = pr.create.job.Lammps("lmp1.2")
job.structure = pr.create.structure.ase.bulk("Al", cubic=True)
murn = job.create_job(pr.job_type.Murnaghan, "murn1.2")
murn.run()
os.listdir(os.path.dirname(murn.project_hdf5.file_name))
>>> ['murn1d2_hdf5', 'murn1.2.h5']
```

The expected output would be: 
```
>>> ['murn1d2_hdf5', 'murn1d2.h5']
```

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by pmrv** [comment]
Same as [this issue](https://github.com/pyiron/pyiron_atomistics/issues/645).

**Comment by jan-janssen** [comment]
> Same as [this issue](https://github.com/pyiron/pyiron_atomistics/issues/645).

@pmrv Can you check if it solves your issue? To me they sound at least slightly different.

**Comment by pmrv** [comment]
Why is this not using the [already existing function](https://github.com/pyiron/pyiron_base/blob/35290355c5f847332b008fb2222900a86ae15988/pyiron_base/jobs/job/util.py#L119) to sanitize job names?

**Comment by jan-janssen** [comment]
> Why is this not using the [already existing function](https://github.com/pyiron/pyiron_base/blob/35290355c5f847332b008fb2222900a86ae15988/pyiron_base/jobs/job/util.py#L119) to sanitize job names?

It is

**Pull request merged**
