### PR TITLE
fix dynamic jobs

### PR DESCRIPTION
**Pull request by jan-janssen**
The automatic registration breaks the functionality of dynamic jobs, this is now overwritten with this pull request. @niklassiemer If you have an idea for a more elegant solution, feel free to modify my pull request.

### CODE REVIEW

**Comment by pmrv** [comment]
Can you briefly summarize what the underlying issue is and how this fixes it?

**Comment by niklassiemer** [comment]
Right now, auto-registration of the dynamic jobs adds them to the `JOB_CLASS_DICT` and then loading them fails since they cannot be loaded from the location they have been generated.... 
The point is, they should not be part of the normal `JOB_CLASS_DICT`... For now, I would either merge this, or just change the lookup order to first look into the `JOB_DYN_DICT`. 

We could also use a `ScriptJob` subclass (`SpecificScriptJob`) with just `__init_subclass(cls): pass`, or in general not register `ScriptJob` subclasses, or unregister all jobs in the `JOB_DYN_DICT` to fix this issue.

**Comment by pmrv** [comment]
In that case wouldn't the correct solution be that the automatically generated subclasses also overwrite the autoregistration logic?

**Comment by niklassiemer** [comment]
Yes, in principle I would like that, however, I just tested 
```python
class Some:
    @classmethod
    def __init_subclass__(cls):
        print('subclass!')
class Any(Some):    
    @classmethod
    def __init_subclass__(cls):
        pass
```
which prints 'subclass'. I.e. the `__init_subclass__` of the _parent_ class is called after the class definition. To exclude the auto-registration we then would need something from the class itself inside the __init_subclass__ call in general.

**Comment by jan-janssen** [comment]
> For now, I would either merge this, or just change the lookup order to first look into the `JOB_DYN_DICT`.

In the interest of time, I would also prefer to merge this.

**Comment by jan-janssen** [comment]
I be able to run the workshop I merge this now, we can potentially redo it later.

**Pull request merged**
