### PR TITLE
[patch] Add pack backwards compatibility tests

### PR DESCRIPTION
**Pull request by samwaseda**

### CODE REVIEW

**Comment by jan-janssen** [comment]
You can merge with https://github.com/pyiron/pyiron_base/pull/1613 this includes the fixes for the integration tests. I just wait to merge this until we have the issues with the current `pyiron_base` version fixed. In addition, I created https://github.com/pyiron-dev/debug-pyiron-stack to debug the coupling of `pyiron_base` and `pyiron_atomistics`. I am going to demonstrate both in the next pyiron meeting, but if you have the chance to test them before the meeting and give me some feedback that would be great.

**Comment by samwaseda** [comment]
> You can merge with #1613 this includes the fixes for the integration tests.

Ok I’ll change the destination branch, but right now it looks like it’s failing for something totally different. I’ll fix it first.

**Comment by samwaseda** [comment]
I got the following error for loading a tar file from an older version. I got the feeling that it’s more related to the changes in `from_dict`. Is that possible? @pmrv @jan-janssen 

```python
======================================================================
ERROR: test_import_old_tar (archiving.test_import.TestUnpackingBackwardsCompatibility.test_import_old_tar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyiron_base/pyiron_base/tests/unit/archiving/test_import.py", line 196, in test_import_old_tar
    job = pr.load("toy")
          ^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/project/jobloader.py", line 105, in __call__
    return super().__call__(job_specifier, convert_to_object=convert_to_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/project/jobloader.py", line 76, in __call__
    return self._project.load_from_jobpath(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/project/generic.py", line 1147, in load_from_jobpath
    job = job.to_object()
          ^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/jobs/job/core.py", line 597, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/storage/hdfio.py", line 1172, in to_object
    return _to_object(self, class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/storage/hdfio.py", line 158, in _to_object
    obj.from_hdf(hdf=hdf.open(".."), group_name=hdf.h5_path.split("/")[-1])
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/jobs/job/template.py", line 97, in from_hdf
    GenericJob.from_hdf(self=self, hdf=hdf, group_name=group_name)
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/interfaces/has_dict.py", line 125, in from_dict
    self._from_dict({k: load(v) for k, v in obj_dict.items()}, version)
                        ^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/interfaces/has_dict.py", line 123, in load
    return create_from_dict(inner_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/interfaces/has_dict.py", line 59, in create_from_dict
    obj.from_dict(obj_dict, version)
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/interfaces/has_dict.py", line 125, in from_dict
    self._from_dict({k: load(v) for k, v in obj_dict.items()}, version)
  File "/home/runner/work/pyiron_base/pyiron_base/pyiron_base/jobs/job/extension/server/generic.py", line 585, in _from_dict
    self._data = ServerDataClass(**obj_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Server.__init__() got an unexpected keyword argument 'structure_id'
```

**Comment by jan-janssen** [comment]
Yes, the structure DB was removed in https://github.com/pyiron/pyiron_base/pull/1579

**Comment by pmrv** [comment]
I will patch this as part of the other fixes, it's already in my local branch.

**Comment by pmrv** [comment]
Actually see #1611, it's there already.

**Comment by samwaseda** [comment]
Ok this backwards compatibility tests are so far useless because they don’t fail when I revert changes made by Jan in the last PR. I have to figure out how to do it…

**Comment by samwaseda** [comment]
I tried to see that the tests fail for reverting the [fix made by @jan-janssen](https://github.com/pyiron/pyiron_base/pull/1616) but there was no success. Frankly I don’t understand how the calphy tests could fail but not the ones I introduced here, but at the end of the day, it only means that `pack` and `unpack` are mostly backward compatible, so I’ll leave it like this.

**Comment by samwaseda** [comment]
Ah and I don’t know really the hierarchy of the current open PR’s, but since this PR needs the changes made in #1611, I changed the destination path to `server`.

**Pull request merged**
