### PR TITLE
Updates to FileTable 

### LINKED ISSUE #1073: FileTable not updating its path
More fundamentally, the `Singleton` class is not updating its attributes like I expect on re-instantiation. This is the source of the current failures on #951.

MWE:
```python
from pyiron_base import Project
from pyiron_base.database.filetable import FileTable

pr = Project('tmp')
f = FileTable(pr.path)
print(f._project)
>>> ".../tmp"

pr2 = Project('tmp2')
f2 = FileTable(pr2.path)
print(f._project)
>>> ".../tmp"
print(f2._project)
>>> ".../tmp" 
# This last one needs to be ".../tmp2"!!!!
```

With the database turned off, projects are re-instantiating a `FilePath` with their own path [here](https://github.com/pyiron/pyiron_base/blob/c1a02fe54b64080215e971c3d8ab0cba2b8d7cf0/pyiron_base/project/generic.py#L139). But if _any other project_ has already done this, then the path is ignored.

I'll fix this tomorrow. Right now I'm of the opinion that `Singleton` needs to handle re-instantiation better, but that opinion is subject to change once I start working on it.

### PR DESCRIPTION
**Pull request by jan-janssen**
Fixes: https://github.com/pyiron/pyiron_base/issues/1073

Combines: https://github.com/pyiron/pyiron_base/pull/1076 and https://github.com/pyiron/pyiron_base/pull/1093 

Creating a separate pull request on the `main` branch triggers the unit tests while a pull request on from one branch to the next does not.

### CODE REVIEW

**Comment by liamhuber** [comment]
> Creating a separate pull request on the `main` branch triggers the unit tests while a pull request on from one branch to the next does not.

In principle that's fine if what you're trying to do is a stacked PR. If you target this one to another branch, then merge that branch to main, it will automatically rebase onto main, and at that point I think the tests will get run

**Comment by jan-janssen** [comment]
@liamhuber Can you take another look? I implemented your suggestions and would like to merge this pull request ideally before the end of the week, as we have a hackathon coming up next week.

**Comment by liamhuber** [comment]
> @liamhuber Can you take another look? I implemented your suggestions and would like to merge this pull request ideally before the end of the week, as we have a hackathon coming up next week. 

For sure. Will get back to you by the end of the day.

**Comment by liamhuber** [comment]
@jan-janssen, I left two more comments on #1093, but I would accept it being merged as-is.

What then is the purpose for this PR? Was it just to force CI on the whole shebang? From my perspective #1076 fixes the bug, then #1093 makes things more efficient. There's no fundamental problem to leaving the code in the #1076 state, so we can just merge those two in relatively quick succession and close this.

**Pull request merged**
