### PR TITLE
increase job_name character limit 50 -> 250

### LINKED ISSUE #959: pyiron database refuses names that are too long (50 chars?)
To replicate the error:

`archive_job = job_obj.copy_to(job_obj.project, new_job_name = "Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0")`

Is there any reason why the limit for database job name character count is set to 50? I find this to be very annoying.

```
---------------------------------------------------------------------------
StringDataRightTruncation                 Traceback (most recent call last)
/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899                 if not evt_handled:
-> 1900                     self.dialect.do_execute(
   1901                         cursor, statement, parameters, context

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    735     def do_execute(self, cursor, statement, parameters, context=None):
--> 736         cursor.execute(statement, parameters)
    737 

StringDataRightTruncation: value too long for type character varying(50)


The above exception was the direct cause of the following exception:

DataError                                 Traceback (most recent call last)
/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/database/generic.py in add_item_dict(self, par_dict)
    858                 )  # make keys lowercase
--> 859                 result = self.conn.execute(
    860                     self.simulation_table.insert(par_dict)

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/database/generic.py in execute(self, *args, **kwargs)
    386     def execute(self, *args, **kwargs):
--> 387         return retry(
    388             lambda: self.execute_once(*args, **kwargs),

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/utils/error.py in retry(func, error, msg, at_most, delay, delay_factor)
    144         try:
--> 145             return func()
    146         except error as e:

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/database/generic.py in <lambda>()
    387         return retry(
--> 388             lambda: self.execute_once(*args, **kwargs),
    389             error=OperationalError,

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/database/generic.py in execute_once(self, *args, **kwargs)
    383                 self._watchdog.kick()
--> 384             return self._conn.execute(*args, **kwargs)
    385 

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in execute(self, statement, *multiparams, **params)
   1379         else:
-> 1380             return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
   1381 

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/sql/elements.py in _execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    333         if _force or self.supports_execution:
--> 334             return connection._execute_clauseelement(
    335                 self, multiparams, params, execution_options

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _execute_clauseelement(self, elem, multiparams, params, execution_options)
   1571         )
-> 1572         ret = self._execute_context(
   1573             dialect,

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1942         except BaseException as e:
-> 1943             self._handle_dbapi_exception(
   1944                 e, statement, parameters, cursor, context

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2123             elif should_wrap:
-> 2124                 util.raise_(
   2125                     sqlalchemy_exception, with_traceback=exc_info[2], from_=e

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    210         try:
--> 211             raise exception
    212         finally:

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899                 if not evt_handled:
-> 1900                     self.dialect.do_execute(
   1901                         cursor, statement, parameters, context

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/default.py in do_execute(self, cursor, statement, parameters, context)
    735     def do_execute(self, cursor, statement, parameters, context=None):
--> 736         cursor.execute(statement, parameters)
    737 

DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(50)

[SQL: INSERT INTO jobs_cmmc (parentid, masterid, projectpath, project, job, subjob, chemicalformula, status, hamilton, hamversion, username, computer, timestart, timestop, totalcputime) VALUES (%(parentid)s, %(masterid)s, %(projectpath)s, %(project)s, %(job)s, %(subjob)s, %(chemicalformula)s, %(status)s, %(hamilton)s, %(hamversion)s, %(username)s, %(computer)s, %(timestart)s, %(timestop)s, %(totalcputime)s) RETURNING jobs_cmmc.id]
[parameters: {'parentid': None, 'masterid': None, 'projectpath': '/cmmc/u/', 'project': 'hmai/project-NiGBs-New/Ni-PureGBs-noGammaShift_testing/S11_RA110_S113/GB/', 'job': 'Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0', 'subjob': '/Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0', 'chemicalformula': 'Ni88', 'status': 'finished', 'hamilton': 'Vasp', 'hamversion': '5.4.4_mpi_AutoReconverge', 'username': 'hmai', 'computer': 'hmai@cmti001#120#cm', 'timestart': datetime.datetime(2022, 12, 15, 18, 20, 1, 941619), 'timestop': datetime.datetime(2022, 12, 16, 13, 41, 13, 898029), 'totalcputime': 69671.0}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/tmp/xpython_26875/3598631569.py in <cell line: 1>()
----> 1 archive_job = job_obj.copy_to(job_obj.project, new_job_name = "Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0")

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/jobs/job/generic.py in copy_to(self, project, new_job_name, input_only, new_database_entry, delete_existing_job, copy_files)
    547 
    548         # Call the copy_to() function defined in the JobCore
--> 549         new_job_core, file_project, hdf5_project, reloaded = self._internal_copy_to(
    550             project=project,
    551             new_job_name=new_job_name,

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/jobs/job/generic.py in _internal_copy_to(self, project, new_job_name, new_database_entry, copy_files, delete_existing_job)
    490 
    491         # Call the copy_to() function defined in the JobCore
--> 492         new_job_core, file_project, hdf5_project, reloaded = super(
    493             GenericJob, self
    494         )._internal_copy_to(

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/jobs/job/core.py in _internal_copy_to(self, project, new_job_name, new_database_entry, copy_files, delete_existing_job)
    726         if self.job_id:
    727             if new_database_entry:
--> 728                 _copy_database_entry(
    729                     new_job_core=new_job_core,
    730                     job_copied_id=self.job_id,

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/jobs/job/util.py in _copy_database_entry(new_job_core, job_copied_id)
     42         db_entry["projectpath"] = new_job_core.project_hdf5.root_path
     43         del db_entry["id"]
---> 44         job_id = new_job_core.project.db.add_item_dict(db_entry)
     45         new_job_core.reset_job_id(job_id=job_id)
     46 

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/database/generic.py in add_item_dict(self, par_dict)
    864                 return result
    865             except Exception as except_msg:
--> 866                 raise ValueError("Error occurred: " + str(except_msg))
    867         else:
    868             raise PermissionError("Not avilable in viewer mode.")

ValueError: Error occurred: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(50)

[SQL: INSERT INTO jobs_cmmc (parentid, masterid, projectpath, project, job, subjob, chemicalformula, status, hamilton, hamversion, username, computer, timestart, timestop, totalcputime) VALUES (%(parentid)s, %(masterid)s, %(projectpath)s, %(project)s, %(job)s, %(subjob)s, %(chemicalformula)s, %(status)s, %(hamilton)s, %(hamversion)s, %(username)s, %(computer)s, %(timestart)s, %(timestop)s, %(totalcputime)s) RETURNING jobs_cmmc.id]
[parameters: {'parentid': None, 'masterid': None, 'projectpath': '/cmmc/u/', 'project': 'hmai/project-NiGBs-New/Ni-PureGBs-noGammaShift_testing/S11_RA110_S113/GB/', 'job': 'Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0', 'subjob': '/Ni_bulk_S11_RA110_S113_JobRefiner_Relaxation_1_Try_0', 'chemicalformula': 'Ni88', 'status': 'finished', 'hamilton': 'Vasp', 'hamversion': '5.4.4_mpi_AutoReconverge', 'username': 'hmai', 'computer': 'hmai@cmti001#120#cm', 'timestart': datetime.datetime(2022, 12, 15, 18, 20, 1, 941619), 'timestop': datetime.datetime(2022, 12, 16, 13, 41, 13, 898029), 'totalcputime': 69671.0}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
```

### PR DESCRIPTION
**Pull request by ligerzero-ai**
see title

### CODE REVIEW

**Comment by pmrv** [comment]
This actually also needs work on the database server, so it's not as easy as this.  (I think at least, I still don't know how sqlalchemy works).

**Comment by ligerzero-ai** [comment]
So I guess the quick and dirty fix would be to initiate my own instance of a pyiron database?

a la 

https://github.com/pyiron/pyiron_base/issues/589#issuecomment-1126219868%20that%20might%20help%20to%20keep%20things%20out%20of%20the%20database.%20Of%20course%20only%20before%20you%20run%20the%20jobs...

from pyiron import Project
pr = Project(path='your_proj')
pr.state.update({
    'sql_file': './pyiron.db',
    'sql_type': 'SQLite',
})

**Comment by ligerzero-ai** [comment]
> This actually also needs work on the database server, so it's not as easy as this. (I think at least, I still don't know how sqlalchemy works).

I can confirm that it didn't work :) I guess I will work with a separate database then

**Comment by pmrv** [comment]
> So I guess the quick and dirty fix would be to initiate my own instance of a pyiron database?
> 
> a la
> 
> [#589 (comment)](https://github.com/pyiron/pyiron_base/issues/589#issuecomment-1126219868)...
> 
> from pyiron import Project pr = Project(path='your_proj') pr.state.update({ 'sql_file': './pyiron.db', 'sql_type': 'SQLite', })

Yeah, I guess that should work.

**Comment by pmrv** [comment]
I made it a draft, so we can keep it as a reminder.

**Pull request closed without merging**
