### PR TITLE
fix mpi support for script job

### LINKED ISSUE #712: Mpi4py enable flag does not work as expected
Looking at the code, I just recognized:
```
from pyiron_base import Project
pr = Project('.')
job = pr.create.job.ScriptJob('name')
job.script_path= './script.py'
job.enable_mpi4py()
job.server.cores = 10
job.executable
>>>['mpirun', '-np', '1', 'python', '/mnt/c/Users/Siemer/pyiron/projects/name_hdf5/name/script.py']
```
Thus, how many cores are used depends on the order of execution!

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by max-hassani** [comment]
@jan-janssen, shall we merge this to create a new release for pyiron_base?
If you think it is necessary, I can make a test on the cluster. But it requires some modification to pyiron-resouces-mpi repo.

**Comment by jan-janssen** [comment]
@niklassiemer Originally raised the issue in https://github.com/pyiron/pyiron_base/issues/712 so I am waiting for him to test it.

**Comment by jan-janssen** [comment]
> But it requires some modification to pyiron-resouces-mpi repo.

This pull request does not require any change to the pyiron resources.

**Comment by jan-janssen** [comment]
@niklassiemer Can you quickly test this?

**Comment by niklassiemer** [comment]
I will try to have a look tomorrow, don't feel well today.

**Comment by niklassiemer** [comment]
Right now, just running your initial example https://github.com/pyiron/pyiron_base/pull/637#issue-1106028227 does not run and raises a `Type` error since `Exectuable.__str__` returns a list. I actually think we mess around with the mpi implementation right now. Wouldn't it be clearer to have a `ScriptExectuable` doing the logic of  `_executable_command` on demand? This way we would not need an extra `enable_mpi` or the like.

**Comment by jan-janssen** [comment]
> Wouldn't it be clearer to have a `ScriptExectuable` doing the logic of `_executable_command` on demand? This way we would not need an extra `enable_mpi` or the like.

Yes, we have an issue for this https://github.com/pyiron/pyiron_base/issues/726 - still my hope would be to get this bug fix merged before as I try to emphasize the application of pyiron beyond atomistic simulations.

**Comment by jan-janssen** [comment]
> Right now, just running your initial example [#637 (comment)](https://github.com/pyiron/pyiron_base/pull/637#issue-1106028227) does not run and raises a `Type` error since `Exectuable.__str__` returns a list. 

The Typeerror is fixed now.

**Comment by niklassiemer** [comment]
Yes, triggering the type error is fixed and the overall fix requires less 'hacking'. I think this is ok! I just fixed also the underlying `TypeError` in `Exectuable.__str__` by returning `str(self.executable_path)`.

**Pull request merged**
