### PR TITLE
[patch] Use tempfile instead of creating a directory

### PR DESCRIPTION
**Pull request by samwaseda**
Another try for [this PR](https://github.com/pyiron/pyiron_base/pull/1555)

### CODE REVIEW

**Comment by samwaseda** [comment]
I will merge this one as soon as all (especially Windows) tests pass because there's no functional change with this PR.

**Comment by samwaseda** [comment]
and of course windows failed...

**Comment by samwaseda** [comment]
I see an underlying problem with `relpath`. I will rewrite this PR to resolve this issue.

**Comment by jan-janssen** [comment]
```
======================================================================
ERROR: test_export_with_targz_extension (archiving.test_export.TestPack.test_export_with_targz_extension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\pyiron_base\pyiron_base\tests\unit\archiving\test_export.py", line 91, in test_export_with_targz_extension
    self.pr.pack(
  File "D:\a\pyiron_base\pyiron_base\pyiron_base\project\generic.py", line 1980, in pack
    destination_path = os.path.relpath(destination_path, os.getcwd())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 783, in relpath
ValueError: path is on mount 'C:', start on mount 'D:'

----------------------------------------------------------------------
```

**Pull request merged**
