### PR TITLE
Add FlattenedStorage.list_arrays

### PR DESCRIPTION
**Pull request by pmrv**
Needed for pyiron_contrib.

### CODE REVIEW

**Comment by pmrv** [comment]
For some reason, only the 3.8 tests take >30min and I can't figure out why...

**Comment by niklassiemer** [comment]
This seems to be a general problem right now... actually also for the coverage workflow. 

EDIT: 
It is 3.9 which fails - this I actually understand even less since 3.8 and 3.10 are ok!?

**Comment by niklassiemer** [comment]
Furthermore, it 'fails' with 
```
----------------------------------------------------------------------
Ran 407 tests in 28.854s

OK (skipped=48)
TestWithProject: Setting up test project
TestWithProject: Setting up test project
Error: The action has timed out.
```

**Comment by pmrv** [comment]
> Furthermore, it 'fails' with
> 
> ```
> ----------------------------------------------------------------------
> Ran 407 tests in 28.854s
> 
> OK (skipped=48)
> TestWithProject: Setting up test project
> TestWithProject: Setting up test project
> Error: The action has timed out.
> ```

Ok, I'll merge this then, but it's a bit weird. :S

**Pull request merged**
