### PR TITLE
Migrate InputList to Datacontainer

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
At least we now get the same errors: 
```
======================================================================
1967
FAIL: test_get_scf_group (sphinx.test_base.TestSphinx)
1968
----------------------------------------------------------------------
1969
Traceback (most recent call last):
1970
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 327, in test_get_scf_group
1971
    self.assertEqual(len(w), 1)
1972
AssertionError: 3 != 1
1973

1974
======================================================================
1975
FAIL: test_validate_ready_to_run (sphinx.test_base.TestSphinx)
1976
----------------------------------------------------------------------
1977
Traceback (most recent call last):
1978
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 449, in test_validate_ready_to_run
1979
    self.assertTrue(self.sphinx.validate_ready_to_run())
1980
AssertionError: False is not true
1981

1982
======================================================================
1983
FAIL: test_write_input (sphinx.test_base.TestSphinx)
1984
----------------------------------------------------------------------
1985
Traceback (most recent call last):
1986
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 218, in test_write_input
1987
    self.assertEqual(file_content, lines)
1988
AssertionError: Lists differ: ['//j[138 chars]cies {\n', '\t\tname = "Fe";\n', '\t\tpotType [1705 chars]}\n'] != ['//j[138 chars]cies = {\'name\': \'"Fe"\', \'potType\': \'"At[1690 chars]}\n']
1989

1990
First differing element 7:
1991
'\tspecies {\n'
1992
'\tspecies = {\'name\': \'"Fe"\', \'potType\': \'"At[71 chars]};\n'
1993

1994
First list contains 5 additional elements.
1995
First extra element 83:
1996
'\t}\n'
1997

1998
Diff is 2391 characters long. Set self.maxDiff to None to see it.
1999

2000
----------------------------------------------------------------------
2001
Ran 375 tests in 417.132s
```

**Comment by liamhuber** [comment]
Ahhh, ok, I think I get it! It took me a while, but I just had to look up the `-v` argument for grep 😝 

Nonetheless, I still feel a little unqualified to review this. @jan-janssen and/or @pmrv would you be kind enough to do some hand-holding for me?

If I understand, the key magic is happening in setting up the environment for the compatibility tests:

```diff
name: Setup
  shell: bash -l {0}
  run: |
    pip install --no-deps .
    cd .. 
    git clone https://github.com/pyiron/pyiron_atomistics
    cd pyiron_atomistics
-   conda env update --name test --file .ci_support/environment.yml
+   grep -v "pyiron_base" .ci_support/environment.yml > environment.yml
+   conda env update --name test --file environment.yml
    python .ci_support/pyironconfig.py
    pip install --no-deps .
```

Here is what I understand:
- `pip install --no-deps .` builds everything using whatever is in the current `pyiron_base` branch we're working on
- `cd/git cone/cd` gets us the other code base and moves into it
- OLD: `conda env update --name test --file .ci_support/environment.yml` overwrote the entire env *including* pyiron_base, so we no longer had our current branch code!
- NEW: Now we update everything *except* pyiron base
- Then we carry on with installation

If this is all a correct understanding, then I'm very happy with the solution. Very elegant patch with the use of `grep -v`, @jan-janssen.

**Comment by liamhuber** [comment]
> At least we now get the same errors:

~~@jan-janssen I still don't follow this comment -- the tests are passing here, where can I get that error? I think I'm just not looking in the right spot!~~

Nevermind, I was just blind

**Comment by jan-janssen** [comment]
> > At least we now get the same errors:
> 
> @jan-janssen I still don't follow this comment -- the tests are passing here, where can I get that error? I think I'm just not looking in the right spot!

We now get this error for the compatibility test: 
```
Compatibility with pyiron_atomistics / build (pull_request) Failing after 10m — build
```
This is the same error I got when I updated `pyiron_atomistics` https://github.com/pyiron/pyiron_atomistics/pull/132

**Comment by liamhuber** [comment]
> > > At least we now get the same errors:
> > 
> > 
> > @jan-janssen I still don't follow this comment -- the tests are passing here, where can I get that error? I think I'm just not looking in the right spot!
> 
> We now get this error for the compatibility test:
> 
> ```
> Compatibility with pyiron_atomistics / build (pull_request) Failing after 10m — build
> ```
> 
> This is the same error I got when I updated `pyiron_atomistics` [pyiron/pyiron_atomistics#132](https://github.com/pyiron/pyiron_atomistics/pull/132)

Haha, yes! I was just totally bind, sorry for the ping!

**Comment by liamhuber** [comment]
I would like to propose the following: 
- re-base this branch onto master and only reapplying the commits after 2fb7582 -- i.e. drop all the InputList changes.
- Merge this branch into master
- Go back over to ??? and merge the new master into it.

This fix to the test workflow is fine by itself and should get merged into master. The problem is that in all the reverting I've lost track of the ??? branch where the InputList updates live. The only place I see all that work atm is right here. I can dig into the merge history later to see if I can find the right branch/PR to recover to do this, but if either of you have any insight into what went down with the reverts you might be better placed than me to do this.

**Comment by jan-janssen** [comment]
I created this branch primarily for the `Inputlist` changes. Now I created a separate branch for the tests https://github.com/pyiron/pyiron_base/pull/259

**Comment by pmrv** [comment]
I fixed one of the breaking tests in pyiron_atomistics. The other two cases are breaking because the sphinx tests check for the number of warnings raised rather than the specific warnings and `InputList` raises new `DeprecationWarnings` now.  I propose we fix this upstream when bumping the pyiron_base version in atomistics.

**Comment by jan-janssen** [comment]
Waiting for https://github.com/pyiron/pyiron_atomistics/pull/135

**Comment by jan-janssen** [comment]
> I fixed one of the breaking tests in pyiron_atomistics. 

@pmrv Are these changes already included in this pull request?

**Comment by pmrv** [comment]
> > I fixed one of the breaking tests in pyiron_atomistics.
> 
> @pmrv Are these changes already included in this pull request?

The one I mentioned are in https://github.com/pyiron/pyiron_atomistics/pull/135 and the integration tests check against the master branch, so it should work.

**Comment by jan-janssen** [comment]
```
======================================================================
1818
FAIL: test_get_scf_group (sphinx.test_base.TestSphinx)
1819
----------------------------------------------------------------------
1820
Traceback (most recent call last):
1821
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 327, in test_get_scf_group
1822
    self.assertEqual(len(w), 1)
1823
AssertionError: 3 != 1
1824

1825
======================================================================
1826
FAIL: test_validate_ready_to_run (sphinx.test_base.TestSphinx)
1827
----------------------------------------------------------------------
1828
Traceback (most recent call last):
1829
  File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 449, in test_validate_ready_to_run
1830
    self.assertTrue(self.sphinx.validate_ready_to_run())
1831
AssertionError: False is not true
1832

1833
----------------------------------------------------------------------
1834
Ran 375 tests in 424.086s
```

**Comment by pmrv** [comment]
> ```
> ======================================================================
> 1818
> FAIL: test_get_scf_group (sphinx.test_base.TestSphinx)
> 1819
> ----------------------------------------------------------------------
> 1820
> Traceback (most recent call last):
> 1821
>   File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 327, in test_get_scf_group
> 1822
>     self.assertEqual(len(w), 1)
> 1823
> AssertionError: 3 != 1
> 1824
> 
> 1825
> ======================================================================
> 1826
> FAIL: test_validate_ready_to_run (sphinx.test_base.TestSphinx)
> 1827
> ----------------------------------------------------------------------
> 1828
> Traceback (most recent call last):
> 1829
>   File "/home/runner/work/pyiron_base/pyiron_atomistics/tests/sphinx/test_base.py", line 449, in test_validate_ready_to_run
> 1830
>     self.assertTrue(self.sphinx.validate_ready_to_run())
> 1831
> AssertionError: False is not true
> 1832
> 
> 1833
> ----------------------------------------------------------------------
> 1834
> Ran 375 tests in 424.086s
> ```

As I said both of these are due to new deprecation warnings raised by the `InputList`.  The first one explicitly checks against the number of warnings raised during the tests and `validate_ready_to_run` also checks the number of warnings raised internally.  This number obviously changes now, since `InputList` raises new ones (and we want that).  I think both issues are better fixed in a PR on pyiron_atomistics on the pyiron_base version bump, since this PR cannot change the tests of pyiron_atomistics.

**Comment by jan-janssen** [comment]
> As I said both of these are due to new deprecation warnings raised by the `InputList`.  The first one explicitly checks against the number of warnings raised during the tests and `validate_ready_to_run` also checks the number of warnings raised internally.  This number obviously changes now, since `InputList` raises new ones (and we want that).  I think both issues are better fixed in a PR on pyiron_atomistics on the pyiron_base version bump, since this PR cannot change the tests of pyiron_atomistics.

I missed the warnings: 
```
2021-03-22 10:48:33,014 - pyiron_log - INFO - run job: job_non_modal id: 1, status: created
1256
job.input.structure != job.structure. The current job.structure will overwrite any changes you may might have made to job.input.structure in the meantime. To disable this overwrite, set job.input.structure.read_only = True. To disable this warning, call job.load_structure_group() after making changes to job.structure.
1257
WARNING:
1258
pyiron_base.generic.inputlist.__init__ is deprecated: use DataContainer instead. It is not guaranteed to be in service in vers. 0.3.0
1259
pyiron_base.generic.inputlist.__init__ is deprecated: use DataContainer instead. It is not guaranteed to be in service in vers. 0.3.0
1260
pyiron_base.generic.inputlist.__init__ is deprecated: use DataContainer instead. It is not guaranteed to be in service in vers. 0.3.0
1261
pyiron_base.generic.inputlist.__init__ is deprecated: use DataContainer instead. It is not guaranteed to be in service in vers. 0.3.0
1262
```

Then it is ready to merge from my perspective.

**Pull request merged**
