### PR TITLE
Accelerate removing of jobs by removing consistency check

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Review by niklassiemer — COMMENTED** [review]
I am ok with these changes - it is a huge performance bottleneck!
Do we plan to handle cases where a sub-job of a Master is deleted in some way in the database? or do we just say it is not that important, especially with the workflow based pyiron coming up? (Or did I understand something wrong?)

**Comment by jan-janssen** [comment]
> Do we plan to handle cases where a sub-job of a Master is deleted in some way in the database? or do we just say it is not that important, especially with the workflow based pyiron coming up? (Or did I understand something wrong?)

That part is still handled in the `remove_job()` function.

**Comment by niklassiemer** [comment]
Ok, it is handled in `JobCore.remove`. Then I do not see any issue with this!

**Comment by XzzX** [comment]
There is a lot of conversion between `job` and `jobid` always involving a database query. Allowing `job` as an argument to `remove_job` can reduce the number of database queries even more.

**Pull request merged**
