### PR TITLE
Support Pandas DataFrame in the DataContainer

### PR DESCRIPTION
**Pull request by jan-janssen**
This is primarily used for Scriptjobs to submit the current state of a dataset for analysis.

### CODE REVIEW

**Comment by pmrv** [comment]
The underlying problem is that `DataFrame` defines its own `to_hdf` that is independent of ours?

**Comment by pmrv** [comment]
I'm not quite happy with having to special case the `DataFrame` on both writing and reading.  I'll think about it today if there's not another way to do it.

**Comment by pmrv** [comment]
I see that in `FileHDFio` we make a similar thing to allow saving dataframes

https://github.com/pyiron/pyiron_base/blob/20f31a7e30c03dc392cdf4d430d52acb90e6493d/pyiron_base/generic/hdfio.py#L646

The easiest solution is probably to check for `DataFrame` and pass them through to `FileHDFio` that seems to know how to handle them.  I've implemented this in #420.

**Comment by jan-janssen** [comment]
Clou this in favor of https://github.com/pyiron/pyiron_base/pull/420

**Pull request closed without merging**
