### PR TITLE
Remove the internal _run_manually method

### PR DESCRIPTION
**Pull request by niklassiemer**
I did not find a usage of that function and it is actually doing the same as `run_if_manually`.

### CODE REVIEW

**Comment by jan-janssen** [comment]
What about https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/runfunction.py#L95 ?

**Review by jan-janssen — CHANGES_REQUESTED** [review]
We still need this function, even if it is not included in the tests. But I agree that we should add a test to prevent this kind of confusion in future.

**Comment by niklassiemer** [comment]
The line you mentioned calls run_if_manually not the internal _run_manually function. Pycharm told me there is no usage of the second one?

**Review by jan-janssen — APPROVED** [review]

**Comment by pmrv** [comment]
I think one source of the confusion is that the function in the `runfunction` module call methods on the job object even though the methods just call back into the original module.  That would actually be a nice refactor for our tutorial workshop.

**Pull request merged**
