### PR TITLE
Update integration tests

### PR DESCRIPTION
**Pull request by jan-janssen**
This pull request fixes the issues with the integration tests. In addition, this pull request adds a compatibility test for notebooks in `pyiron_atomistics`.

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
======================================================================
ERROR: test_transform_trajectory (atomic.job.test_transform_trajectory.TestTransformTrajectory.test_transform_trajectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/atomic/job/test_transform_trajectory.py", line 37, in test_transform_trajectory
    self.project.unpack("get_structure_test")
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 2004, in unpack
    import_archive.import_jobs(self, archive_directory=origin_path)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/archiving/import_archive.py", line 54, in import_jobs
    df, common_path = transfer_files(
                      ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/archiving/import_archive.py", line 109, in transfer_files
    copytree(os.path.join(origin_path, common_path), project_path, dirs_exist_ok=True)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'get_structure_test/get_structure_test/lmp'

======================================================================
ERROR: test_run (atomic.master.test_murnaghan_master_modal.TestMurnaghan.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/atomic/master/test_murnaghan_master_modal.py", line 61, in test_run
    self.project.wait_for_job(murn, interval_in_s=5, max_iterations=50)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1701, in wait_for_job
    wait_for_job(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/extension/server/queuestatus.py", line 244, in wait_for_job
    raise ValueError(
ValueError: Maximum iterations reached, but the job was not finished.

======================================================================
ERROR: test_run (atomic.master.test_murnaghan_non_modal.TestMurnaghan.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/atomic/master/test_murnaghan_non_modal.py", line 71, in test_run
    self.project.wait_for_job(murn, interval_in_s=5, max_iterations=50)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1701, in wait_for_job
    wait_for_job(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/extension/server/queuestatus.py", line 244, in wait_for_job
    raise ValueError(
ValueError: Maximum iterations reached, but the job was not finished.

======================================================================
ERROR: test_Chemical_Element_to_and_from_hdf (atomic.structure.test_periodic_table.TestPeriodicTable.test_Chemical_Element_to_and_from_hdf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/atomic/structure/test_periodic_table.py", line 97, in test_Chemical_Element_to_and_from_hdf
    test_ham.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_Chemical_Element_to_and_from_hdf_with_None_Parent (atomic.structure.test_periodic_table.TestPeriodicTable.test_Chemical_Element_to_and_from_hdf_with_None_Parent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/atomic/structure/test_periodic_table.py", line 116, in test_Chemical_Element_to_and_from_hdf_with_None_Parent
    test_ham.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_output (calphy.test_base.TestCalphy.test_output)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/calphy/test_base.py", line 162, in test_output
    self.output_project.unpack("test_files")
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 2004, in unpack
    import_archive.import_jobs(self, archive_directory=origin_path)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/archiving/import_archive.py", line 54, in import_jobs
    df, common_path = transfer_files(
                      ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/archiving/import_archive.py", line 109, in transfer_files
    copytree(os.path.join(origin_path, common_path), project_path, dirs_exist_ok=True)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_files/test_files/calphy_unittest'

======================================================================
ERROR: test_serialization (gpaw.test_gpaw.TestGpaw.test_serialization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/gpaw/test_gpaw.py", line 34, in test_serialization
    loaded.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/gpaw/gpaw.py", line 116, in from_hdf
    super(Gpaw, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/gpaw/pyiron_ase.py", line 40, in from_hdf
    super(AseJob, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: AtomisticGenericJob.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: tearDownClass (testing.test_exampleAtomisticJob.TestExampleJob)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/testing/test_exampleAtomisticJob.py", line 38, in tearDownClass
    job = project.load(project.get_job_ids()[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 105, in __call__
    return super().__call__(job_specifier, convert_to_object=convert_to_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 76, in __call__
    return self._project.load_from_jobpath(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/project.py", line 333, in load_from_jobpath
    job = super(Project, self).load_from_jobpath(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1147, in load_from_jobpath
    job = job.to_object()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/core.py", line 597, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 1172, in to_object
    return _to_object(self, class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 158, in _to_object
    obj.from_hdf(hdf=hdf.open(".."), group_name=hdf.h5_path.split("/")[-1])
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/testing/randomatomistic.py", line 461, in from_hdf
    super(AtomisticExampleJob, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/testing/randomatomistic.py", line 228, in from_hdf
    super(ExampleJob, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: AtomisticGenericJob.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_fix_iso (thermodynamics.test_interface.TestHessianJob.test_fix_iso)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/thermodynamics/test_interface.py", line 78, in test_fix_iso
    job = self.job.copy()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 490, in copy
    _job_reload_after_copy(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/util.py", line 620, in _job_reload_after_copy
    job.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_fix_z_dir (thermodynamics.test_interface.TestHessianJob.test_fix_z_dir)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/thermodynamics/test_interface.py", line 93, in test_fix_z_dir
    job = self.job.copy()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 490, in copy
    _job_reload_after_copy(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/util.py", line 620, in _job_reload_after_copy
    job.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_half_velocity (thermodynamics.test_interface.TestHessianJob.test_half_velocity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/thermodynamics/test_interface.py", line 86, in test_half_velocity
    job = self.job.copy()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 490, in copy
    _job_reload_after_copy(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/util.py", line 620, in _job_reload_after_copy
    job.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_job_creation (thermodynamics.test_interface.TestHessianJob.test_job_creation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/thermodynamics/test_interface.py", line 73, in test_job_creation
    job = self.job.copy()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 490, in copy
    _job_reload_after_copy(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/util.py", line 620, in _job_reload_after_copy
    job.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py", line 499, in from_hdf
    super(LammpsInteractive, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: LammpsBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_run_complete (vasp.test_vasp.TestVasp.test_run_complete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/vasp/test_vasp.py", line 421, in test_run_complete
    job_chg_den = self.job_complete.restart_from_charge_density(job_name="chg")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 1521, in restart_from_charge_density
    new_ham = self.restart(job_name=job_name, job_type=job_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 1430, in restart
    new_ham = super(VaspBase, self).restart(job_name=job_name, job_type=job_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/atomistics/job/atomistic.py", line 454, in restart
    new_ham = super(AtomisticGenericJob, self).restart(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1332, in restart
    new_ham = self.copy_to(
              ^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 709, in copy_to
    new_job_core, file_project, hdf5_project, reloaded = self._internal_copy_to(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 654, in _internal_copy_to
    )._internal_copy_to(
      ^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/core.py", line 790, in _internal_copy_to
    new_job_core = self.copy()
                   ^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 490, in copy
    _job_reload_after_copy(
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/util.py", line 620, in _job_reload_after_copy
    job.from_hdf()
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 778, in from_hdf
    super(VaspBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: VaspBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_import (vasp.test_vasp_import.TestVaspImport.test_import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/vasp/test_vasp_import.py", line 33, in test_import
    ham = self.project.load("full_job_sample")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 105, in __call__
    return super().__call__(job_specifier, convert_to_object=convert_to_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 76, in __call__
    return self._project.load_from_jobpath(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/project.py", line 333, in load_from_jobpath
    job = super(Project, self).load_from_jobpath(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1147, in load_from_jobpath
    job = job.to_object()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/core.py", line 597, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 1172, in to_object
    return _to_object(self, class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 158, in _to_object
    obj.from_hdf(hdf=hdf.open(".."), group_name=hdf.h5_path.split("/")[-1])
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 778, in from_hdf
    super(VaspBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: VaspBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: test_import_bader (vasp.test_vasp_import.TestVaspImport.test_import_bader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/vasp/test_vasp_import.py", line 84, in test_import_bader
    ham = self.project.load("bader_test")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 105, in __call__
    return super().__call__(job_specifier, convert_to_object=convert_to_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 76, in __call__
    return self._project.load_from_jobpath(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/project.py", line 333, in load_from_jobpath
    job = super(Project, self).load_from_jobpath(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1147, in load_from_jobpath
    job = job.to_object()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/core.py", line 597, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 1172, in to_object
    return _to_object(self, class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 158, in _to_object
    obj.from_hdf(hdf=hdf.open(".."), group_name=hdf.h5_path.split("/")[-1])
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 778, in from_hdf
    super(VaspBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: VaspBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
ERROR: setUpClass (vasp.test_vasp_restart.TestVaspRestart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/vasp/test_vasp_restart.py", line 49, in setUpClass
    cls.timeout_job = cls.project.load("full_job_sample")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 105, in __call__
    return super().__call__(job_specifier, convert_to_object=convert_to_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/jobloader.py", line 76, in __call__
    return self._project.load_from_jobpath(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/project.py", line 333, in load_from_jobpath
    job = super(Project, self).load_from_jobpath(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/project/generic.py", line 1147, in load_from_jobpath
    job = job.to_object()
          ^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/core.py", line 597, in to_object
    return self.project_hdf5.to_object(object_type, **qwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 1172, in to_object
    return _to_object(self, class_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/hdfio.py", line 158, in _to_object
    obj.from_hdf(hdf=hdf.open(".."), group_name=hdf.h5_path.split("/")[-1])
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/pyiron_atomistics/vasp/base.py", line 778, in from_hdf
    super(VaspBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/interactive.py", line 364, in from_hdf
    super(InteractiveBase, self).from_hdf(hdf=hdf, group_name=group_name)
  File "/Users/runner/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/jobs/job/generic.py", line 1245, in from_hdf
    self.from_dict(obj_dict=job_dict)
TypeError: VaspBase.from_dict() got an unexpected keyword argument 'obj_dict'

======================================================================
FAIL: test_vasp_import (table.test_datamining.TestDatamining.test_vasp_import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pyiron_base/pyiron_atomistics/tests/table/test_datamining.py", line 62, in test_vasp_import
    self.assertTrue(df["Convergence"].values[0])
AssertionError: None is not true

----------------------------------------------------------------------
```

**Comment by pmrv** [comment]
I'll use this branch for all changes, but we might still need some synchronous changes from the atomistics side to make everything work.

**Comment by pmrv** [comment]
So strangely copying lammps jobs works locally the `server` branch from base and the dependabot branch from atomistics, but I'm trying with the [debug repo](https://github.com/pmrv/debug-pyiron-stack/pull/1) now.

**Comment by jan-janssen** [comment]
I thought the issue was about copying Sphinx jobs.

**Comment by pmrv** [comment]
Ah, I got confused between the error messages.  Copying a `TemplateJob` *did* work, but I'll have to dig into it later.

**Comment by jan-janssen** [comment]
Wait for https://github.com/pyiron/pyiron_base/pull/1620

**Comment by jan-janssen** [comment]
```
File ~/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/interfaces/has_dict.py:129, in HasDict.from_dict(self, obj_dict, version)
    127 if version is None:
    128     version = obj_dict.get("DICT_VERSION", None)
--> 129 self._from_dict({k: load(v) for k, v in obj_dict.items()}, version)

File ~/miniconda3/envs/my-env/lib/python3.12/site-packages/pyiron_base/storage/datacontainer.py:1041, in DataContainer._from_dict(self, obj_dict, version)
   1039 def _from_dict(self, obj_dict, version=None):
   1040     if version == "0.2.0":
-> 1041         order = obj_dict.pop("KEY_ORDER")
   1042     else:
   1043         order = None

KeyError: 'KEY_ORDER'

Input Notebook:  notebooks/data_mining.ipynb
Output Notebook: notebooks/data_mining-out.ipynb
```

**Comment by jan-janssen** [comment]
@pmrv Can you take a look at this?

**Comment by pmrv** [comment]
I reopened it in #1637 for easier rebasing onto the server branch.

**Pull request closed without merging**
